# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uo3G_-09L-00ND-lOO6HDlqB-r7cBeKB
"""

# app_final.py — AI Personalization (FAR-Trans Hybrid Recommender)
# Full version (UPDATED):
# ✅ Risk-segmented similarity (Aggressive->Aggressive etc.)
# ✅ 2-month stability gate (last ~60 days volatility)
# ✅ MiFID-style suitability policy filter
# ✅ LEFT SIDEBAR FILTER: Customer Risk Segment (filters CustomerID dropdown)
# ✅ OPTIONAL: shows 60-day volatility per recommended asset + stability pass/fail + strict/relaxed toggle
# ✅ Fix: Transactions CSV download uses transactions (not recommendations)
#
# Run:
#   streamlit run app_final.py
#
# NOTE:
# - Risk Segment is shown in the UI caption/remarks, so we DO NOT add a redundant customerRiskLevel column in the table.

from pathlib import Path
import numpy as np
import pandas as pd
import streamlit as st
from scipy.sparse import coo_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import cosine_similarity
import matplotlib.pyplot as plt
import textwrap

# ---------------- PATH SETUP ----------------
APP_DIR = Path(__file__).parent.resolve()
CANDIDATE_DIRS = [
    Path("/content"),  # Colab default
    Path("/Users/rajanraorane/Documents/UL/AI_Personalization_Demo"),  # Your Mac
    APP_DIR,
]
DATA_DIR = next((p.resolve() for p in CANDIDATE_DIRS if p.exists()), APP_DIR)


def read_csv_here(name: str) -> pd.DataFrame:
    p1 = DATA_DIR / name
    if p1.exists():
        return pd.read_csv(p1)
    p2 = APP_DIR / name
    if p2.exists():
        return pd.read_csv(p2)
    raise FileNotFoundError(f"Could not find '{name}' in {DATA_DIR} or {APP_DIR}")


# ---------------- RISK POLICY ----------------
RISK_TO_ALLOWED = {
    "Conservative": {"Bond", "MTF"},
    "Income": {"Bond", "MTF"},
    "Balanced": {"Bond", "MTF", "Stock"},
    "Aggressive": {"Stock", "MTF"},
    "Not Provided": {"Bond", "MTF"},  # safe default
}

# Base (relaxed) 2-month volatility thresholds (tunable)
STABILITY_THRESHOLDS_RELAXED = {
    "Conservative": 0.020,
    "Income": 0.025,
    "Balanced": 0.035,
    "Aggressive": 0.060,
    "Not Provided": 0.030,
}

# Strict thresholds (OPTIONAL toggle)
STABILITY_THRESHOLDS_STRICT = {
    "Conservative": 0.015,
    "Income": 0.020,
    "Balanced": 0.028,
    "Aggressive": 0.050,
    "Not Provided": 0.022,
}


def normalize_risk(risk) -> str:
    if risk is None or (isinstance(risk, float) and np.isnan(risk)):
        return "Not Provided"
    r = str(risk).strip()
    if not r or r.lower() in {"nan", "none"}:
        return "Not Provided"
    r = r.title()
    fixes = {
        "Aggresive": "Aggressive",
        "Conservativ": "Conservative",
        "Income ": "Income",
    }
    return fixes.get(r, r)


# ---------------- DATA LOADING ----------------
@st.cache_data(show_spinner=False)
def load_data():
    customers = read_csv_here("customer_information.csv")
    transactions = read_csv_here("transactions.csv")
    assets = read_csv_here("asset_information.csv")
    limit_prices = read_csv_here("limit_prices.csv")
    close_prices = read_csv_here("close_prices.csv")

    tx = (
        transactions
        .merge(customers, on="customerID", how="left")
        .merge(assets, on=["ISIN", "marketID"], how="left")
        .merge(limit_prices[["ISIN", "profitability"]], on="ISIN", how="left")
    )
    tx["timestamp"] = pd.to_datetime(tx["timestamp"], errors="coerce")

    # Normalize categories to reduce label mismatch
    if "assetCategory" in assets.columns:
        assets["assetCategory"] = assets["assetCategory"].astype(str).str.strip().str.title()

    return customers, transactions, assets, limit_prices, close_prices, tx


# ---------------- STABILITY (2-MONTH) ----------------
@st.cache_data(show_spinner=False)
def compute_2m_volatility(close_prices: pd.DataFrame, days: int = 60) -> pd.Series:
    """
    2-month stability metric = volatility (std of daily returns) over last ~60 calendar days.
    Returns: Series index ISIN -> vol_60d
    """
    cp = close_prices.copy()
    cp["timestamp"] = pd.to_datetime(cp["timestamp"], errors="coerce")
    cp = cp.dropna(subset=["timestamp", "ISIN", "closePrice"])

    last_dt = cp["timestamp"].max()
    cutoff = last_dt - pd.Timedelta(days=days)

    cp = cp[cp["timestamp"] >= cutoff].sort_values(["ISIN", "timestamp"])
    cp["ret"] = cp.groupby("ISIN")["closePrice"].pct_change()
    vol_60d = cp.groupby("ISIN")["ret"].std()
    return vol_60d


# ---------------- INTERACTIONS ----------------
def prepare_interactions(tx: pd.DataFrame, allowed_customers=None):
    pos = tx[tx["transactionType"].astype(str).str.lower() == "buy"].copy()
    pos = pos.dropna(subset=["customerID", "ISIN", "totalValue"])

    if allowed_customers is not None:
        pos = pos[pos["customerID"].isin(allowed_customers)].copy()

    pos["weight"] = np.log1p(pos["totalValue"].clip(lower=0))

    user_ids = pd.Index(pos["customerID"].unique(), name="customerID")
    item_ids = pd.Index(pos["ISIN"].unique(), name="ISIN")

    u2i = {u: i for i, u in enumerate(user_ids)}
    i2i = {v: i for i, v in enumerate(item_ids)}

    pos["u"] = pos["customerID"].map(u2i)
    pos["i"] = pos["ISIN"].map(i2i)

    R = coo_matrix(
        (pos["weight"], (pos["u"], pos["i"])),
        shape=(len(user_ids), len(item_ids))
    ).tocsr()

    return pos, R, user_ids, item_ids, u2i, i2i


# ---------------- CONTENT FEATURES ----------------
def compute_content_features(assets: pd.DataFrame,
                            limit_prices: pd.DataFrame,
                            close_prices: pd.DataFrame,
                            item_ids: pd.Index):
    cp = close_prices.copy()
    cp["timestamp"] = pd.to_datetime(cp["timestamp"], errors="coerce")
    cp = cp.dropna(subset=["timestamp", "ISIN", "closePrice"])
    cp = cp.sort_values(["ISIN", "timestamp"])
    cp["ret"] = cp.groupby("ISIN")["closePrice"].pct_change()
    vol_all = cp.groupby("ISIN")["ret"].std().rename("volatility").reset_index()

    asset_feat = (
        assets.drop_duplicates("ISIN")
        .merge(limit_prices[["ISIN", "profitability"]], on="ISIN", how="left")
        .merge(vol_all, on="ISIN", how="left")
    )

    for col in ["profitability", "volatility"]:
        med = asset_feat[col].median()
        asset_feat[col] = asset_feat[col].fillna(med)

    cat_cols = ["assetCategory", "sector", "industry"]
    for c in cat_cols:
        if c not in asset_feat.columns:
            asset_feat[c] = "Unknown"

    oh = pd.get_dummies(asset_feat[cat_cols], dummy_na=True)

    num = asset_feat[["profitability", "volatility"]].astype(float)
    num_sc = pd.DataFrame(
        StandardScaler().fit_transform(num),
        columns=num.columns,
        index=asset_feat.index
    )

    X_item = pd.concat([num_sc, oh], axis=1)
    X_item["ISIN"] = asset_feat["ISIN"]
    X_item = X_item.set_index("ISIN").reindex(item_ids).fillna(0)
    return X_item


# ---------------- SIMILARITY ----------------
def prepare_similarity(R, X_item):
    item_vecs = R.T.tocsc()
    item_norms = np.sqrt(np.asarray(item_vecs.multiply(item_vecs).sum(axis=1)).ravel()) + 1e-9

    sims_content = cosine_similarity(X_item.values)
    np.fill_diagonal(sims_content, 0.0)
    return item_vecs, item_norms, sims_content


def top_similar_items_cf(item_vecs, norms, item_index, topn=100):
    v = item_vecs[item_index, :]
    v_norm = float(np.sqrt(v.multiply(v).sum())) + 1e-9

    num = np.asarray((item_vecs @ v.T).todense()).ravel()
    sims = np.divide(num, norms * v_norm, out=np.zeros_like(num), where=norms > 0)

    sims[item_index] = -1.0
    k = min(topn, len(sims) - 1)
    top_idx = np.argpartition(-sims, k)[:k]
    top_idx = top_idx[np.argsort(-sims[top_idx])]
    return top_idx, sims[top_idx]


# ---------------- SEGMENT MODEL BUILD (cached) ----------------
@st.cache_resource(show_spinner=False)
def build_segment_model(segment_key: str,
                        tx: pd.DataFrame,
                        customers: pd.DataFrame,
                        assets: pd.DataFrame,
                        limit_prices: pd.DataFrame,
                        close_prices: pd.DataFrame):
    """
    Build CF + CBF model only for customers in the same risk segment.
    """
    seg_customers = customers.copy()
    seg_customers["risk_norm"] = seg_customers["riskLevel"].apply(normalize_risk)

    allowed_customers = seg_customers.loc[
        seg_customers["risk_norm"] == segment_key, "customerID"
    ].unique()

    pos_s, R_s, user_ids_s, item_ids_s, u2i_s, i2i_s = prepare_interactions(tx, allowed_customers=allowed_customers)

    X_item_s = compute_content_features(assets, limit_prices, close_prices, item_ids_s)
    item_vecs_s, norms_s, sims_c_s = prepare_similarity(R_s, X_item_s)

    return {
        "pos": pos_s,
        "R": R_s,
        "user_ids": user_ids_s,
        "item_ids": item_ids_s,
        "u2i": u2i_s,
        "i2i": i2i_s,
        "X_item": X_item_s,
        "item_vecs": item_vecs_s,
        "norms": norms_s,
        "sims_c": sims_c_s,
    }


# ---------------- RECOMMENDER ----------------
def recommend_for_user(customer_id, alpha, topn,
                       customers, tx, assets, limit_prices, close_prices,
                       vol_60d: pd.Series,
                       strict_stability: bool = False):
    """
    Risk-segmented CF + 2-month stability gate + suitability filtering.
    Returns: rec_isins, reasons, risk, threshold
    """
    cust_row = customers[customers["customerID"] == customer_id].tail(1)
    risk = normalize_risk(cust_row["riskLevel"].values[0] if not cust_row.empty else None)

    model = build_segment_model(risk, tx, customers, assets, limit_prices, close_prices)

    R = model["R"]
    item_ids = model["item_ids"]
    u2i = model["u2i"]
    item_vecs = model["item_vecs"]
    norms = model["norms"]
    sims_content = model["sims_c"]

    thresholds = STABILITY_THRESHOLDS_STRICT if strict_stability else STABILITY_THRESHOLDS_RELAXED
    thresh = thresholds.get(risk, thresholds["Not Provided"])

    # Vol aligned to segment item universe
    v = vol_60d.reindex(item_ids)
    v_fill = v.fillna(v.median() if pd.notna(v.median()) else 0.0)

    # cold-start within the segment
    if customer_id not in u2i:
        seg_buy = model["pos"]
        pop = (seg_buy.groupby("ISIN")["totalValue"].sum().sort_values(ascending=False))
        recs = list(pop.index)

        # Apply stability gate + suitability for cold-start too
        recs = [r for r in recs if float(v_fill.get(r, v_fill.median())) <= thresh]

        allowed = RISK_TO_ALLOWED.get(risk, None)
        if allowed:
            cats = assets.drop_duplicates("ISIN").set_index("ISIN")["assetCategory"]
            recs = [r for r in recs if str(cats.get(r, "")).strip().title() in allowed]

        recs = recs[:topn]
        reasons = [f"Popular among {risk} customers (segment-based) + passed stability gate"] * len(recs)
        return recs, reasons, risk, thresh

    u = u2i[customer_id]
    owned = set(R[u].indices)

    # CF score (within segment)
    cf = np.zeros(len(item_ids))
    for i in owned:
        top_idx, sim = top_similar_items_cf(item_vecs, norms, i, topn=200)
        cf[top_idx] += sim

    # Content score
    cont = sims_content[list(owned)].mean(axis=0) if owned else np.zeros(len(item_ids))

    # Hybrid score
    score = alpha * cf + (1 - alpha) * cont
    score[list(owned)] = -np.inf

    # 2-month stability gate
    stable_mask = (v_fill <= thresh).values
    score = np.where(stable_mask, score, -np.inf)

    # MiFID suitability filter
    allowed = RISK_TO_ALLOWED.get(risk, None)
    if allowed:
        cats = assets.drop_duplicates("ISIN").set_index("ISIN")["assetCategory"].reindex(item_ids)
        mask = cats.astype(str).str.strip().str.title().isin(allowed).fillna(False).values
        score = np.where(mask, score, -np.inf)

    # Top-N
    valid = np.where(score > -np.inf)[0]
    if len(valid) == 0:
        return [], [], risk, thresh

    k = min(topn, len(valid))
    top_idx = np.argpartition(-score, k - 1)[:k]
    top_idx = top_idx[np.argsort(-score[top_idx])]
    rec_isins = list(item_ids[top_idx])

    reasons = [
        f"Segment-based ({risk}) similarity + passed 2-month stability gate + fits suitability policy."
        for _ in rec_isins
    ]
    return rec_isins, reasons, risk, thresh


# ---------------- LABEL HELPERS ----------------
def _wrap_label(s: str, width: int = 12, max_lines: int = 2) -> str:
    if not isinstance(s, str):
        return "N/A"
    words = " ".join(s.split())
    lines = textwrap.wrap(words, width=width)[:max_lines]
    if len(textwrap.wrap(words, width=width)) > max_lines:
        lines[-1] = lines[-1][:max(0, width - 1)] + "…"
    return "\n".join(lines)


def _customer_display(customers: pd.DataFrame, cid):
    row = customers.loc[customers["customerID"] == cid].head(1)
    if row.empty:
        return f"Customer {cid}", ""
    r = row.iloc[0].to_dict()

    name_parts = []
    for c in ["firstName", "first_name", "givenName", "given_name", "name"]:
        if c in r and pd.notna(r[c]) and str(r[c]).strip():
            name_parts.append(str(r[c]).strip())
            break
    for c in ["lastName", "last_name", "surname", "familyName", "family_name"]:
        if c in r and pd.notna(r[c]) and str(r[c]).strip():
            name_parts.append(str(r[c]).strip())
            break
    name = " ".join(name_parts) if name_parts else f"Customer {cid}"

    addr_parts = []
    for c in ["address", "street", "city", "state", "country", "postcode", "zip"]:
        if c in r and pd.notna(r[c]) and str(r[c]).strip():
            addr_parts.append(str(r[c]).strip())
    address = ", ".join(addr_parts)
    return name, address


# ---------------- STREAMLIT APP ----------------
def main():
    st.set_page_config(page_title="AI-Driven Personalization and Ethics in Banking", page_icon="💡", layout="wide")

    # Styling + Header
    st.markdown("""
    <style>
    [data-testid="stAppViewContainer"] > .main {
        background-color: #0E1117;
        color: #FAFAFA;
        font-family: "Helvetica Neue", sans-serif;
    }
    h1, h2, h3 { color: #00BFA5; }
    .stMetricValue, .stMetricLabel { color: #FAFAFA !important; }
    .small-note { color:#9aa0a6; font-size:0.9rem; }
    .big { font-size: 1.2rem; }
    </style>
    """, unsafe_allow_html=True)

    st.markdown("""
    <div style="text-align:center;">
        <img src="https://www.ul.ie/themes/custom/ul/logo.svg" width="200">
        <h1 style="margin-bottom:0;">AI-Driven Personalization and Ethics in Banking</h1>
        <p style="color:gray; margin-top:5px;"> Recommendations • Governance • Ethics</p>
    </div>
    <hr>
    """, unsafe_allow_html=True)

    with st.spinner("Loading datasets..."):
        customers, transactions, assets, limit_prices, close_prices, tx = load_data()
        vol_60d = compute_2m_volatility(close_prices, days=60)

    # Prepare risk-normalized column for sidebar filtering (demo convenience)
    customers = customers.copy()
    customers["risk_norm"] = customers["riskLevel"].apply(normalize_risk)

    # Sidebar
    st.sidebar.header("⚙️ Settings")

    # NEW: Risk segment filter for customer dropdown (filters list only)
    st.sidebar.markdown("### 🧑‍💼 Customer Filters")
    risk_options = ["All"] + sorted(customers["risk_norm"].dropna().unique().tolist())
    risk_filter = st.sidebar.selectbox("Customer Risk Segment", risk_options, index=0)
    if risk_filter != "All":
        customer_pool = customers.loc[customers["risk_norm"] == risk_filter, "customerID"].unique()
    else:
        customer_pool = customers["customerID"].unique()
    st.sidebar.caption("Customer list filtered for demo only. Recommendations use the selected customer's actual risk level.")

    selected = st.sidebar.selectbox("CustomerID", sorted(customer_pool))

    alpha = st.sidebar.slider("Blend (α):", 0.0, 1.0, 0.6, 0.05)
    topn = st.sidebar.slider("Top-N Recommendations", 5, 20, 10, 1)

    f_sector = st.sidebar.multiselect("Filter by Sector", sorted(assets["sector"].dropna().unique()))
    f_industry = st.sidebar.multiselect("Filter by Industry", sorted(assets["industry"].dropna().unique()))
    st.sidebar.markdown("---")

    # OPTIONAL: stability strictness toggle
    st.sidebar.markdown("### 📉 Stability Settings")
    strict_stability = st.sidebar.checkbox("Strict 2-month stability filtering (safer)", value=False)

    # Consent gate
    st.sidebar.markdown("---")
    st.sidebar.markdown("### 🔐 Data Use & Consent")
    user_consented = st.sidebar.checkbox("I confirm lawful use/consent for personalization", value=True)

    # KPIs
    pos_all = tx[tx["transactionType"].astype(str).str.lower() == "buy"]
    k1, k2, k3 = st.columns(3)
    k1.metric("Users w/ BUYs", f"{pos_all['customerID'].nunique():,}")
    k2.metric("Asset Universe", f"{pos_all['ISIN'].nunique():,}")
    k3_placeholder = k3.empty()

    tab1, tab2, tab3, tab4 = st.tabs(["🏦 Recommendations", "📊 Transactions", "🏛 Governance", "🌱 Ethics"])

    out = pd.DataFrame()

    # --- RECOMMENDATIONS ---
    with tab1:
        if not user_consented:
            st.info("Enable consent in the sidebar to generate recommendations.")
        else:
            recs, reasons, risk, thresh = recommend_for_user(
                selected, alpha, topn,
                customers, tx, assets, limit_prices, close_prices,
                vol_60d,
                strict_stability=strict_stability
            )

            if len(recs) == 0:
                st.warning("No recommendations found (after stability + suitability filters).")
            else:
                meta = (
                    assets.drop_duplicates("ISIN")
                    .set_index("ISIN")[["assetName", "assetCategory", "sector", "industry", "marketID"]]
                    .reindex(recs).reset_index()
                )
                perf = limit_prices.set_index("ISIN")[["profitability"]].reindex(recs).reset_index()
                out = meta.merge(perf, on="ISIN", how="left")
                out["reason"] = reasons[:len(out)]

                # OPTIONAL: show 60-day vol + pass/fail
                out["volatility_60d"] = vol_60d.reindex(out["ISIN"]).values
                out["stability_threshold"] = float(thresh)
                out["stability_pass"] = out["volatility_60d"].fillna(out["volatility_60d"].median()) <= thresh

                # optional user filters
                if f_sector:
                    out = out[out["sector"].isin(f_sector)]
                if f_industry:
                    out = out[out["industry"].isin(f_industry)]

                k3_placeholder.metric("Avg Profitability (Top-N)", f"{out['profitability'].mean():.2f}")

                st.subheader(f"Recommendations for Customer {selected}")
                st.caption(
                    f"Risk Segment: **{risk}** • Stability window: **60 days** • "
                    f"Stability mode: **{'Strict' if strict_stability else 'Relaxed'}** • Suitability enforced."
                )

                st.data_editor(
                    out[
                        [
                            "ISIN", "assetName", "assetCategory", "sector", "industry", "marketID",
                            "profitability",
                            "volatility_60d", "stability_threshold", "stability_pass",
                            "reason"
                        ]
                    ],
                    hide_index=True, disabled=True, use_container_width=True
                )

                # Profitability chart
                fig, ax = plt.subplots(figsize=(11, 5))
                labels = out["assetName"].fillna("N/A").apply(lambda s: _wrap_label(s, width=12, max_lines=2))
                heights = out["profitability"].fillna(0).astype(float)
                bars = ax.bar(labels, heights, edgecolor="#0E1117", linewidth=0.5)

                for b in bars:
                    h = b.get_height()
                    ax.text(
                        b.get_x() + b.get_width() / 2,
                        h + (0.05 if h >= 0 else -0.15),
                        f"{h:.2f}",
                        ha="center",
                        va="bottom" if h >= 0 else "top",
                        fontsize=9
                    )

                ax.set_ylabel("Profitability", fontsize=11)
                ax.set_title("Profitability (Top-N)", fontsize=15, fontweight="bold", color="#00BFA5", pad=10)
                ax.grid(axis="y", linestyle="--", linewidth=0.6, alpha=0.4)
                plt.xticks(rotation=30, ha="right", fontsize=9)
                plt.yticks(fontsize=9)
                plt.tight_layout()
                st.pyplot(fig)

                with st.expander("💬 Why these were recommended?"):
                    cust_name, cust_addr = _customer_display(customers, selected)
                    where_bit = f" from {cust_addr}" if cust_addr else ""
                    avg_prof = float(out["profitability"].fillna(0).mean()) if not out.empty else 0.0
                    allowed = ", ".join(sorted(RISK_TO_ALLOWED.get(risk, {"N/A"})))

                    st.markdown(f"""
**Customer Profile:** {cust_name}{where_bit}
**Risk Segment:** **{risk}**
**Suitability Policy (allowed categories):** **{allowed}**
**Stability Gate:** last **60 days** volatility threshold applied (**{thresh:.3f}**)
**Stability Mode:** **{'Strict' if strict_stability else 'Relaxed'}**

**Reason for Recommendation:**
- Similarity is computed **within the same risk segment** (e.g., Aggressive → Aggressive).
- Recommended assets must pass a **2-month stability filter**, reducing short-term volatility exposure.
- Assets are then filtered by **risk suitability policy** (MiFID-style constraint).
- Average historical profitability for the Top-N is **{avg_prof:.2f}** (past performance ≠ future results).
- This prototype supports **human advisors** and does not automate investment decisions.
                    """)

                st.download_button(
                    "⬇️ Download Recommendations (CSV)",
                    out.to_csv(index=False),
                    file_name=f"recommendations_{selected}.csv",
                    mime="text/csv"
                )
                st.caption("**Disclaimer:** Assistive prototype only — not investment advice.")

    # --- TRANSACTIONS ---
    with tab2:
        st.subheader("Recent BUY Transactions")
        recent = (
            tx[(tx["customerID"] == selected) & (tx["transactionType"].astype(str).str.lower() == "buy")]
            .sort_values("timestamp", ascending=False)
            .head(20)[["timestamp", "ISIN", "assetName", "assetCategory", "totalValue", "units"]]
        )
        st.data_editor(recent, hide_index=True, disabled=True, use_container_width=True)

        # FIX: download transactions, not recommendations
        st.download_button(
            "⬇️ Download Customer Statement (CSV)",
            recent.to_csv(index=False),
            file_name=f"transactions_{selected}.csv",
            mime="text/csv"
        )
        st.caption("Top 20 recent BUY transactions for this customer.")

    # --- GOVERNANCE ---
    with tab3:
        st.subheader("Policy & Compliance")
        policy_rows = {
            "Framework": [
                "GDPR (2016/2018)",
                "MiFID II (2018)",
                "Internal Risk–Suitability Policy",
                "EU AI Act (2024)",
                "Transparency / Explainability"
            ],
            "Requirement": [
                "Lawful basis / consent before personalization",
                "Suitability checks (product matches client risk)",
                "Enforce allowed categories per risk profile",
                "Risk documentation & human oversight for higher-risk AI",
                "Provide reasons users can understand"
            ],
            "Status": ["PASS", "PASS", "PASS", "INCOMPLETE", "PASS"],
            "Evidence / Notes": [
                "User consent confirmed in app",
                "Segment-based + suitability policy enforced",
                "Allowed categories per risk profile applied",
                "Need DPIA + documented risk classification for production",
                "Plain-English reasons provided"
            ]
        }
        st.data_editor(pd.DataFrame(policy_rows), hide_index=True, disabled=True, use_container_width=True)

        st.subheader("Sign-off")
        approver_df = pd.DataFrame({
            "Approver Name": ["Priya Menon", "Liam O’Connor", "Sara Novak", "Alan Murphy"],
            "Role": ["Model Risk Manager", "Compliance Officer", "Data Protection Officer (DPO)", "Head of Advisory"]
        })
        st.data_editor(approver_df, hide_index=True, disabled=True, use_container_width=True)

    # --- ETHICS ---
    with tab4:
        st.subheader("Responsible AI Framework & Stewardship Roles")
        st.caption("This outlines how Responsible AI values are implemented and overseen by governance roles.")

        ethics_data = {
            "Principle": [
                "Fairness",
                "Transparency & Explainability",
                "Accountability",
                "Non-Maleficence (Do No Harm)",
                "Human Oversight",
                "Privacy & Data Protection"
            ],
            "Implementation": [
                "Risk-segmented similarity prevents cross-group recommendation bias.",
                "Each recommendation includes a plain-English reason.",
                "Governance artefacts can be audited; policies are explicit.",
                "Stability gate reduces short-term volatility exposure.",
                "Human-in-the-loop via α blend and filters; recommendations are assistive.",
                "Dataset is anonymized; production use requires DPIA & minimization."
            ],
            "Approver": [
                "Model Risk Manager",
                "AI Ethics Committee",
                "Compliance Officer",
                "Chief Risk Officer (CRO)",
                "Business Owner",
                "Data Protection Officer (DPO)"
            ]
        }
        st.data_editor(pd.DataFrame(ethics_data), hide_index=True, disabled=True, use_container_width=True)

        st.download_button("⬇️ Download Audit Log (JSON)", data="[]", file_name="audit_log.json", mime="application/json")

    st.markdown("<hr><div style='text-align:center;color:gray'>© 2025 Rajan Raorane • MSc AI • University of Limerick</div>", unsafe_allow_html=True)


if __name__ == "__main__":
    main()